pt13/app.py
from factories import (
    create_app,
    configure_error_handlers,
    configure_jinja,
    configure_blueprints,
    configure_extensions
)

app = create_app(
    DEBUG=True,
    SECRET_KEY='secret-here',
    # DEBUG_TB_PROFILER_ENABLED=True,
    # DEBUG_TB_TEMPLATE_EDITOR_ENABLED=True
)

configure_error_handlers(app)
configure_jinja(app)
configure_blueprints(app)

# blueprints can be registered here directly
from blueprints import contact
app.register_blueprint(contact.blueprint)
# NOTE: Changes in endpoints, now got blueprint.endpoint

# add extra extensions
configure_extensions(app)

pt13/blueprints/contact/__init__.py
from flask import Blueprint, render_template
from .form import ContactForm
from .db import db

blueprint = Blueprint('contact', __name__, template_folder='templates')


@blueprint.route('/contact/', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        db.contact.insert(form.data)
        return "Mensagem enviada com sucesso!"
    return render_template('contact.html', form=form)

pt13/blueprints/home.py
from flask import Blueprint, render_template

blueprint = Blueprint('home', __name__)


@blueprint.route('/')
def home():
    return render_template('ok.html')


@blueprint.app_template_global()
def foo():
    return 'bar'

pt13/blueprints/mistake.py
from flask import Blueprint, abort

blueprint = Blueprint('mistake', __name__)


@blueprint.route('/mistake/')
def mistake():
    # this causes Internal Server Error
    return abort(500)

pt13/blueprints/secret.py
# TODO: protect with simplelogin
from flask import Blueprint, abort

blueprint = Blueprint('secret', __name__)


@blueprint.route('/secret/')
def secret():
    # this causes Foridden (user not authorized)
    return abort(403)

pt13/flask_simplelogin/__init__.py
# example from https://github.com/rochacbruno/flask_simple_sitemap

from functools import wraps
from flask import (
    Blueprint, render_template, abort, session,
    request, redirect, flash, url_for
)
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('name', validators=[DataRequired()])
    password = PasswordField('message', validators=[DataRequired()])


def default_login_checker(user):
    """user must be a dictionary here default is
    checking username/password
    if login is ok returns True else False
    In real implementation this function goes to database
    and checks login credentials.
    """
    username = user.get('username')
    password = user.get('password')
    if username == 'admin' and password == 'secret':
        return True
    return False


def is_logged_in():
    return 'logged_in' in session


def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            flash("You need to login first")
            return redirect(url_for('simple_login.login'))
    return wrap


class SimpleLogin(object):
    """Simple Flask Login"""

    def __init__(self, app=None, login_checker=None):
        self.config = {
            'blueprint': 'simple_login',
            'login_url': '/login/',
            'logout_url': '/logout/',
            'home_url': '/'
        }
        self.app = None
        self.login_checker = None
        if app is not None:
            self.init_app(app=app, login_checker=login_checker)

    def init_app(self, app, login_checker=None):
        self.login_checker = login_checker or default_login_checker
        self._register(app)
        self._load_config()
        self._register_views()
        self._register_extras()

    def _register(self, app):
        if not hasattr(app, 'extensions'):
            app.extensions = {}

        if 'simple_login' in app.extensions:
            raise RuntimeError("Flask extension already initialized")

        app.extensions['simple_login'] = self
        self.app = app

    def _load_config(self):
        self.config.update(
            self.app.config.get_namespace(
                namespace='SIMPLE_LOGIN_',
                lowercase=True,
                trim_namespace=True
            )
        )

    def _register_views(self):
        self.blueprint = Blueprint(
            self.config['blueprint'],
            __name__,
            template_folder='templates'
        )

        self.blueprint.add_url_rule(
            self.config['login_url'],
            endpoint='login',
            view_func=self.login,
            methods=['GET', 'POST']
        )

        self.blueprint.add_url_rule(
            self.config['logout_url'],
            endpoint='logout',
            view_func=self.logout,
            methods=['GET']
        )

        self.app.register_blueprint(self.blueprint)

    def _register_extras(self):
        self.app.add_template_global(is_logged_in)

    def login(self):
        destiny = request.args.get(
            'next', default=self.config.get('home_url', '/')
        )
        if is_logged_in():
            flash('already logged in')
            return redirect(destiny)

        form = LoginForm()
        if form.validate_on_submit():
            if self.login_checker(form.data):
                flash("login success!!")
                session['logged_in'] = True
                return redirect(destiny)
            else:
                flash('invalid credentials')
        return render_template('login.html', form=form)

    def logout(self):
        session.clear()
        flash('Logged out!')
        return redirect(self.config.get('home_url', '/'))

pt13/templates/error.html
{% extends "layout.html" %}
{% block title %}{{ error.name }}{% endblock %}
{% block body %}
  <h1> {{ error.name }}</h1>
  <p>{{ error.description }}</p>
  <img src="https://http.cat/{{error.code}}" alt="{{ error }}">
  <p><a href="{{ url_for('home.home') }}">go somewhere nice</a>
{% endblock %}

pt13/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Awesome {% endblock %}</title>
    {% block head %}
        <!-- TODO: use url_for here: -->
        <link rel="stylesheet" href="/static/bootstrap.min.css">
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
<a class="navbar-brand" href="#">Mysite</a>
{% block nav %}
<!-- TODO: Iterate over a list of menu items to generate menu -->
<div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('contact.contact') }}">Contact</a>
          </li>
        </ul>
      </div>
{% endblock %}
</nav>

<div class="jumbotron">
    <div class="container">

            {% with messages = get_flashed_messages() %}
            {% if messages %}
              <ul class="flashes alert alert-primary">
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
              </ul>
            {% endif %}
            {% endwith %}

        {% block top %}
        <h1 class="display-3">Welcome to my ugly website!!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        {% endblock %}
    </div>
</div>

<div class="container">
{% block body %}
<div class="row">
<p>
    Content comes here!
</p>
</div>
{% endblock %}
</div>

<div class="container">
<footer>
{% block footer %}
    <address>
    Written by <a href="mailto:webmaster@example.com">Jon Doe</a>.<br>
    Visit us at: Example.com Box 564, Disneyland USA<br>
    Copyright 1996
    </address>
{% endblock %}
</footer>
</div>

{% block tail%}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/static/lib.js"></script>
<script>
    hello("World");
</script>
{% endblock %}

</body>
</html>

pt13/templates/ok.html
{% extends "layout.html" %}
{% block title %}Hello!{% endblock %}
{% block body %}
  <h1>Welcome!!</h1>
  <p>Hey it works!!!</p>
  <hr>
  The template global: {{ ulfy("hello world from flask") }}<br>
  The template filter: {{"Hello World From Flask" | listify}}
{% endblock %}